services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: football
      MYSQL_USER: football
      MYSQL_PASSWORD: footballpassword
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./my-db:/var/lib/mysql

  redis:
    image: redislabs/rebloom:2.8.1
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./data:/data
  
  redis-insight:
    image: redislabs/redisinsight:latest
    ports:
      - "5540:5540"
    volumes:
      - ./redisinsight:/db

  backend:
    build: ./backend/.
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: football
      MYSQL_PASSWORD: footballpassword
      MYSQL_DATABASE: football
      FOOTBALL_API_TOKEN: 09c05f78fa8a44f8a2343532c1945ee6
      REDIS_HOST: redis
      REDIS_PORT: 6379
      BLOOM_SIZE: 100
      BLOOM_ERROR_RATE: 0.01
      BLOOM_KEY: 'function_calls'
      SECRET_KEY: "09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"
      ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: 30

    ports:
      - "8000:8000"
  
  frontend:
    build: ./frontend/.
    depends_on:
      # mysql:
      #   condition: service_healthy
      backend:
        condition: service_started
    # environment:
    #   MYSQL_HOST: mysql
    #   MYSQL_USER: football
    #   MYSQL_PASSWORD: footballpassword
    #   FOOTBALL_API_TOKEN: 09c05f78fa8a44f8a2343532c1945ee6
    #   MYSQL_DATABASE: football
    ports:
      - "80:80"

  # mongodb:
  #   image: mongo:8.0.1
  #   container_name: mongodb
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME: root
  #     - MONGO_INITDB_ROOT_PASSWORD: rootpassword
  #     - MONGO_INITDB_DATABASE: football
  #     - MONGO_INITDB_USERNAME: football
  #     - MONGO_INITDB_PASSWORD: footballpassword
  #   ports:
  #     - 27017:27017
    
  # mongo-express:
  #   image: mongo-express:1.0.2
  #   depends_on: mongodb
  #   environment:
  #     - ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
  #     - ME_CONFIG_MONGODB_SERVER: mongodb
  #     - ME_CONFIG_BASICAUTH_USERNAME: football
  #     - ME_CONFIG_BASICAUTH_PASSWORD: footballpassword
  #   ports:
  #     - 8081:8081

  # data_manager:
  #   build: data_manager/.
  #   depends_on:
  #     - redis:
  #       condition: service_healthy
  #     # - mysql:
  #     #     condition: service_healthy
  #     # - mongodb:
  #     #     condition: service_started
  #   environment:
  #     MYSQL_HOST: mysql
  #     MYSQL_USER: football
  #     MYSQL_PASSWORD: footballpassword
  #     FOOTBALL_API_TOKEN: 09c05f78fa8a44f8a2343532c1945ee6
  #     MYSQL_DATABASE: football
  #     BLOOM_SIZE: 100
  #     BLOOM_ERROR_RATE: 0.01
  